#! /bin/bash
#######################################################################
# Jordan Adamson 
#######################################################################
shopt -s expand_aliases
#source $HOME"/.bashrc"

USERNAME=$1

#to kill all the jobs
qstat -u$USERNAME | grep "$USERNAME" | cut -d"." -f1 | xargs qdel

#to kill all the running jobs
qstat -u$USERNAME | grep "R" | cut -d"." -f1 | xargs qdel

#to kill all the queued jobs
qstat -u$USERNAME | grep "Q" | cut -d"." -f1 | xargs qdel


## Clean Up
echo -e 'rm  *.sh.e*  *.sh.o*  *.pbs02.OU  *.Rout'


